version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - revive
    - gocritic
    - errorlint
    - nilerr
    - durationcheck
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    errorlint:
      errorf: true
      asserts: true
      comparison: true
